
/* Autogenerated file, do not edit! */

/* eslint-disable */
import {
  type AbiType,
  AztecAddress,
  type AztecAddressLike,
  CompleteAddress,
  Contract,
  type ContractArtifact,
  ContractBase,
  ContractFunctionInteraction,
  type ContractInstanceWithAddress,
  type ContractMethod,
  type ContractStorageLayout,
  type ContractNotes,
  decodeFromAbi,
  DeployMethod,
  EthAddress,
  type EthAddressLike,
  EventSelector,
  type FieldLike,
  Fr,
  type FunctionSelectorLike,
  loadContractArtifact,
  loadContractArtifactForPublic,
  type NoirCompiledContract,
  NoteSelector,
  Point,
  type PublicKey,
  PublicKeys,
  type Wallet,
  type U128Like,
  type WrappedFieldLike,
} from '@aztec/aztec.js';
import VeilPaymentContractArtifactJson from '../../target/VeilPayment-VeilPayment.json' with { type: 'json' };
export const VeilPaymentContractArtifact = loadContractArtifact(VeilPaymentContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract VeilPayment;
 */
export class VeilPaymentContract extends ContractBase {
  
  private constructor(
    instance: ContractInstanceWithAddress,
    wallet: Wallet,
  ) {
    super(instance, VeilPaymentContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    return Contract.at(address, VeilPaymentContract.artifact, wallet) as Promise<VeilPaymentContract>;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, depositer: AztecAddressLike, issuer: AztecAddressLike) {
    return new DeployMethod<VeilPaymentContract>(PublicKeys.default(), wallet, VeilPaymentContractArtifact, VeilPaymentContract.at, Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, depositer: AztecAddressLike, issuer: AztecAddressLike) {
    return new DeployMethod<VeilPaymentContract>(publicKeys, wallet, VeilPaymentContractArtifact, VeilPaymentContract.at, Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof VeilPaymentContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<VeilPaymentContract['methods'][M]>
  ) {
    return new DeployMethod<VeilPaymentContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      VeilPaymentContractArtifact,
      VeilPaymentContract.at,
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return VeilPaymentContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(VeilPaymentContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'depositer' | 'issuer' | 'clawback_request' | 'key'> {
      return {
        depositer: {
      slot: new Fr(1n),
    },
issuer: {
      slot: new Fr(2n),
    },
clawback_request: {
      slot: new Fr(3n),
    },
key: {
      slot: new Fr(4n),
    }
      } as ContractStorageLayout<'depositer' | 'issuer' | 'clawback_request' | 'key'>;
    }
    

  public static get notes(): ContractNotes<'AddressNote' | 'UintNote' | 'ValueNote'> {
    return {
      AddressNote: {
          id: new NoteSelector(0),
        },
UintNote: {
          id: new NoteSelector(2),
        },
ValueNote: {
          id: new NoteSelector(1),
        }
    } as ContractNotes<'AddressNote' | 'UintNote' | 'ValueNote'>;
  }
  

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** checkClawbackAge(clawback_hash: field, min_age: integer) */
    checkClawbackAge: ((clawback_hash: FieldLike, min_age: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** claimClawback(token: struct, amount: integer, recipient: struct, nonce: field) */
    claimClawback: ((token: AztecAddressLike, amount: (bigint | number), recipient: AztecAddressLike, nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor(depositer: struct, issuer: struct) */
    constructor: ((depositer: AztecAddressLike, issuer: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** deposit(token: struct, recipient: struct, amount: integer) */
    deposit: ((token: AztecAddressLike, recipient: AztecAddressLike, amount: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** initialiateClawback(token: struct, amount: integer, recipient: struct, nonce: field) */
    initialiateClawback: ((token: AztecAddressLike, amount: (bigint | number), recipient: AztecAddressLike, nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** registerClawback(clawback_hash: field) */
    registerClawback: ((clawback_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_private_state() */
    sync_private_state: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** withdraw(token: struct, amount: integer, recipient: struct) */
    withdraw: ((token: AztecAddressLike, amount: (bigint | number), recipient: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };
}
